package org.havenapp.main.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import org.havenapp.main.storage.AppLogger
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM file encryption using Android Keystore.
 *
 * File format: [12-byte IV][ciphertext + GCM tag]
 *
 * Uses streaming CipherOutputStream/CipherInputStream to avoid loading full
 * video files into memory. The key is hardware-backed on supported devices;
 * the OS prevents key extraction.
 *
 * Key alias: "haven_media_key" — created once, reused for all media files.
 *
 * [logger] is wired from HavenApplication after Hilt initializes, so log entries
 * appear in the DiagnosticsScreen ring buffer.
 */
object MediaEncryptionManager {

    private const val TAG = "MediaEncryptionManager"
    private const val KEY_ALIAS = "haven_media_key"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_SIZE = 12
    private const val GCM_TAG_BITS = 128

    /** Set by HavenApplication after Hilt is ready. */
    internal var logger: AppLogger? = null

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance("AndroidKeyStore").also { it.load(null) }
        (ks.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
            .apply {
                init(
                    KeyGenParameterSpec.Builder(
                        KEY_ALIAS,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                    )
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setKeySize(256)
                        .build()
                )
            }
            .generateKey()
    }

    /**
     * Encrypts [inputFile] to [outputFile] using AES-256-GCM.
     *
     * Uses [Cipher.doFinal] rather than [CipherOutputStream] — same correctness
     * rationale as [decryptToFile]: GCM streams poorly through the JCA streaming
     * API on Android. doFinal appends the 16-byte GCM tag automatically.
     */
    fun encryptFile(inputFile: File, outputFile: File) {
        logger?.i(TAG, "encrypt start: ${inputFile.name} (${inputFile.length()} bytes) → ${outputFile.name}")
        runCatching {
            val plainBytes = inputFile.readBytes()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
            val iv = cipher.iv  // 12-byte random IV generated by GCM mode
            val ciphertext = cipher.doFinal(plainBytes)
            outputFile.outputStream().use { out ->
                out.write(iv)
                out.write(ciphertext)
            }
            logger?.i(TAG, "encrypt done: ${outputFile.name} (${outputFile.length()} bytes)")
        }.onFailure { e ->
            logger?.e(TAG, "encrypt failed: ${inputFile.name} — ${e.javaClass.simpleName}: ${e.message}")
            throw e
        }
    }

    /**
     * Decrypts [encryptedFile] (format: [12-byte IV][ciphertext+tag]) to [outputFile].
     *
     * Uses [Cipher.doFinal] on the full ciphertext rather than [CipherInputStream].
     * CipherInputStream with AES-GCM buffers the entire input before releasing any
     * plaintext (GCM must verify the auth tag first), causing indefinite hangs on
     * large files. doFinal is simpler and correct — GCM tag verification happens
     * in one call, then the plaintext is written atomically.
     */
    fun decryptToFile(encryptedFile: File, outputFile: File) {
        logger?.i(TAG, "decrypt start: ${encryptedFile.name} (${encryptedFile.length()} bytes) → ${outputFile.name}")
        runCatching {
            val encBytes = encryptedFile.readBytes()
            val iv = encBytes.copyOfRange(0, IV_SIZE)
            val ciphertext = encBytes.copyOfRange(IV_SIZE, encBytes.size)
            logger?.d(TAG, "decrypt: ciphertext ${ciphertext.size} bytes, initialising cipher")
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
            val plaintext = cipher.doFinal(ciphertext)
            outputFile.writeBytes(plaintext)
            logger?.i(TAG, "decrypt done: ${outputFile.name} (${plaintext.size} bytes written)")
        }.onFailure { e ->
            logger?.e(TAG, "decrypt failed: ${encryptedFile.name} — ${e.javaClass.simpleName}: ${e.message}")
            throw e
        }
    }

    /**
     * Encrypts [inputFile] in place: writes a [inputFile].enc sibling, then deletes the original.
     * @return The absolute path of the encrypted file.
     */
    fun encryptInPlace(inputFile: File): String {
        val encFile = File(inputFile.absolutePath + ".enc")
        encryptFile(inputFile, encFile)
        inputFile.delete()
        logger?.i(TAG, "encryptInPlace: original deleted, enc path: ${encFile.absolutePath}")
        return encFile.absolutePath
    }
}
