package org.havenapp.main.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM file encryption using Android Keystore.
 *
 * File format: [12-byte IV][ciphertext + GCM tag]
 *
 * Uses streaming CipherOutputStream/CipherInputStream to avoid loading full
 * video files into memory. The key is hardware-backed on supported devices;
 * the OS prevents key extraction.
 *
 * Key alias: "haven_media_key" — created once, reused for all media files.
 */
object MediaEncryptionManager {

    private const val KEY_ALIAS = "haven_media_key"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_SIZE = 12
    private const val GCM_TAG_BITS = 128

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance("AndroidKeyStore").also { it.load(null) }
        (ks.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
            .apply {
                init(
                    KeyGenParameterSpec.Builder(
                        KEY_ALIAS,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                    )
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setKeySize(256)
                        .build()
                )
            }
            .generateKey()
    }

    /**
     * Encrypts [inputFile] to [outputFile] using AES-256-GCM.
     * Uses streaming to handle large video files without memory pressure.
     */
    fun encryptFile(inputFile: File, outputFile: File) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv  // 12-byte random IV generated by GCM mode
        outputFile.outputStream().use { out ->
            out.write(iv)
            CipherOutputStream(out, cipher).use { cos ->
                inputFile.inputStream().copyTo(cos)
            }
        }
    }

    /**
     * Decrypts [encryptedFile] (format: [12-byte IV][ciphertext+tag]) to [outputFile].
     */
    fun decryptToFile(encryptedFile: File, outputFile: File) {
        encryptedFile.inputStream().use { input ->
            val iv = ByteArray(IV_SIZE)
            input.read(iv)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
            CipherInputStream(input, cipher).use { cis ->
                outputFile.outputStream().use { out ->
                    cis.copyTo(out)
                }
            }
        }
    }

    /**
     * Encrypts [inputFile] in place: writes a [inputFile].enc sibling, then deletes the original.
     * @return The absolute path of the encrypted file.
     */
    fun encryptInPlace(inputFile: File): String {
        val encFile = File(inputFile.absolutePath + ".enc")
        encryptFile(inputFile, encFile)
        inputFile.delete()
        return encFile.absolutePath
    }
}
